### ISSUE TITLE
[discussion ] CS / SQL

### ISSUE THREAD

**Issue by remicollet** [glpi-project/docdev#1]
Proposal, change "Database queries"  to:

Direct call to $DB->query() should be avoid.

To add / update / delete rows, use the appropriate CommonDBTM methods.

To select data from the DB, use the $DB->request method()

When direct SQL cannot be avoid

... previous content...

**Comment by ddurieux** [comment]
+1

**Comment by trasher** [comment]
I will add (when I'll have some free time) a new page on the doc to document databases call, explaining what yould be avoided and what to use.

Thanks :)

**Comment by trasher** [comment]
DBIterator doc has been added, as well as query() one with a warning on usage... Guess this should be closed ;)
