### ISSUE TITLE
Update plugins doc

### ISSUE THREAD

**Issue by trasher** [glpi-project/docdev#3]
@yllen already wrote some documentation about plugins development in GLPi. It's available here:
https://forge.glpi-project.org/projects/plugins/wiki/Fr_CreatePlugin084

Have to update/fix the plugins part with that one.

**Comment by orthagh** [comment]
For information, i (and anothers glpi dev) did some work on https://github.com/pluginsGLPI/example/wiki
for plugins development.

Some parts are up to date, other not

**Comment by trasher** [comment]
@orthagh thanks. I guess I'll have to work on this in two parts... This will be a huge work.

Could you please consider adding a tip on tat wiki explaining the doc has moved, waiting for rewrite? This could also be done on the redmine wiki I guess.
