### ISSUE TITLE
Github / Rebase

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/docdev#51]
Hello,

I just read the updates of dev doc : great job !
I suggest to add a § on source code management : how to rebase a github fork to keep up to date with the master one.

I usually made inversed pull requests too my repository, but this isn't clean...

If some one could write doc about this, I think it can help some developpers too :)

Regards

**Comment by trasher** [comment]
Hello,

I've already wrote a line about the workflow; see http://glpi-developer-documentation.readthedocs.io/en/master/sourcecode.html#general

While this is not explicit (I'll add a note), the advice is to keep master (and bugfixes) branch on upstream repository; no need to update your fork that way.

**Comment by AnaelMobilia** [comment]
Hi @trasher ,

Thanks for the update.
My - stub - question is how did i keep the master on my fork synchronized with the master of the glpi repository (same for the 9.1 bugfixes, ...)

I fork one time the glpi repository, then I create a first branch to work on it and PR.
Some days later, I create a second branch for another thing and want this branch to be up-to-date of the glpi/master at the time I create the branch.

I duno how to do this technicaly ;-)

Bests regards,
Anael

**Comment by trasher** [comment]
Well... creating a branch for me is done locally with a `git branch -b mybranch` while on the branch I want to work from. Fact is my master branch is always glpi one, not my fork's; so updating myfork/master branch is only done sometimes (mainly to keep uploading my work branches light).

On our local copy, considering your "origin" points to your fork, you can do:
```
$ git co anybranch
$ git branch -d master
$ git remote add upstream https://github.com/glpi-project/glpi.git
$ git fetch upstream
$ git co -b master upstream/master
```

Master branch will always be the good one, you'll just have to `git pull` on it. Then, if you want to update you fork's master branch; just run (while you're on master locally):
```
$ git push origin master
```

If you do not work on master directly (I advice you not to do); it will just be ok. If you've already changed you fork's master; you can drop it before runnign again the last push command.

Hope that helps you :)

**Comment by AnaelMobilia** [comment]
Hello,

Not as easy : my IDE (Netbeans) try on this configuration to commit to the glpi repository and not mine...

The solution I found :
```
[pack]
	buildbitmaps = false
[core]
	symlinks = false
	repositoryformatversion = 0
	filemode = false
	logallrefupdates = true
	bare = false
[remote "origin"]
	url = https://github.com/AnaelMobilia/glpi.git
#	url = https://github.com/glpi-project/glpi.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin/master
	merge = refs/heads/master
```

When i want to update the fork master : switch the url to glpi-project repository, fetch content, switch back to my repository and (command line) git push origin master .

Not really satisying as it need to mix manual modifications and command line with IDE, but it allow to achieve my goal :-)

Thanks for the help !
Regards
