### ISSUE TITLE
DBmysqlIterator

### ISSUE THREAD

**Issue by ipra** [glpi-project/docdev#60]
GLPI v.9.1.6
I think count of DBmysqlIterator return wrong number (see attachement)
![glpi_dbmysqliterator](https://user-images.githubusercontent.com/10263005/29877777-d780b954-8da0-11e7-8112-bf832620941f.JPG)

**Comment by trasher** [comment]
This issue should be reported against GLPI, not the docs. Please also provide a way to reproduce
